In [1]:
import random
import numpy as np

student_names = ['A', 'B', 'C', 'D', 'E']

student_marks = {name: random.randint(0, 100) for name in student_names}

In [2]:
for student, marks in student_marks.items():
    if marks >= 70:
        print(f"{student}: Distinction")
    elif 60 <= marks <= 69:
        print(f"{student}: First Class")
    elif 50 <= marks <= 59:
        print(f"{student}: Second Class")
    elif 40 <= marks <= 49:
        print(f"{student}: Pass")
    else:
        print(f"{student}: Fail")




A: Distinction
B: Fail
C: First Class
D: Pass
E: Pass


In [3]:
arr_1d = np.arange(10)
print("1D Array from 0 to 9:", arr_1d)

arr_even = np.arange(30, 71, 2)
print("Even integers from 30 to 70:", arr_even)

matrix = np.arange(10, 22).reshape(3, 4)
print("3x4 Matrix filled with values from 10 to 21:")
print(matrix)

print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))


1D Array from 0 to 9: [0 1 2 3 4 5 6 7 8 9]
Even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
3x4 Matrix filled with values from 10 to 21:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Sum of all elements: 186
Sum of each column: [42 45 48 51]
Sum of each row: [46 62 78]


: 