In [1]:
import numpy as np
import pandas as pd

a = np.random.normal(size=(3, 3))
b = np.random.normal(size=(3, 3))
result = np.vstack((a, b))
print(result)


[[-0.46447271 -1.36984392  0.10229817]
 [-0.34418981 -0.16797486  1.03772008]
 [-1.08595454  0.47149627 -0.25121622]
 [ 1.44689288 -0.23653634 -0.34521587]
 [-0.85053745  0.10329683 -0.41370521]
 [-0.36612777  0.26006026  0.37675076]]


In [2]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a, b)
print(common_items)


[2 4]


In [3]:
list_series = pd.Series(['a', 'b', 'c', 'd'])
array_series = pd.Series(np.array([1, 2, 3, 4]))
dict_series = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})

df = pd.DataFrame({'List Series': list_series, 'Array Series': array_series, 'Dict Series': dict_series})
print(df)


  List Series  Array Series  Dict Series
0           a           1.0          NaN
1           b           2.0          NaN
2           c           3.0          NaN
3           d           4.0          NaN
a         NaN           NaN          1.0
b         NaN           NaN          2.0
c         NaN           NaN          3.0
d         NaN           NaN          4.0


In [4]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def min_max_scaling(data):
    min_val = np.min(data)
    max_val = np.max(data)
    scaled_data = (data - min_val) / (max_val - min_val)
    return scaled_data

normalized_sepallength = min_max_scaling(sepallength)

print(normalized_sepallength)


[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333